import { Colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    posterWrapper: { width: 120 },
    poster: {
        width: "100%",
        aspectRatio: 2 / 3,
        borderRadius: 16,
        marginBottom: 8,
        backgroundColor: Colors.surfaceLight,
    },
    posterPlaceholder: {
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: Colors.surfaceLight,
    },
    heroBanner: {
        height: 320,
        width: "100%",
        position: "relative",
    },
    bannerGradient: {
        ...StyleSheet.absoluteFill,
    },
    bannerBackgroundImg: {
        width: "100%",
        height: "100%",
    },
    bannerContent: {
        position: "absolute",
        bottom: 10,
        left: 16,
        right: 16,
        flexDirection: "row",
        alignItems: "flex-end",
        gap: 16,
    },
    infoContainer: { flex: 1, gap: 1 },
    titleWrapper: { flexDirection: "row", alignItems: "center", gap: 8 },
    movieTitle: { color: Colors.textPrimary, fontSize: 22, fontWeight: "bold" },
    releaseDate: { color: Colors.textSecondary, fontSize: 14 },
    metaWrapper: { flexDirection: "row", alignItems: "center", gap: 8 },
    duration: { color: Colors.textSecondary, fontSize: 14 },
    dot: { color: Colors.textSecondary, fontSize: 16 },
    genres: { color: Colors.textSecondary, fontSize: 14 },
    movieStats: { flexDirection: "row", marginTop: 8, gap: 4 },
    actionBar: { flexDirection: "row", gap: 8, marginTop: 8 },
    actionBtn: {
        alignItems: "center",
        justifyContent: "center",
        width: 48,
        height: 48,
        borderRadius: 32,
        backgroundColor: Colors.surface,
    },
    actionBtnIcon: { color: Colors.textPrimary, fontSize: 18 },
    overviewWrapper: { paddingHorizontal: 16 },
    overview: { color: Colors.textSecondary },
    expandBtn: {},
    expandBtnText: { color: Colors.textPrimary },
    listItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 14,
        paddingHorizontal: 4,
        borderBottomWidth: 1,
        borderBottomColor: Colors.surface,
    },
    listItemLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flex: 1,
    },
    listItemIcon: {
        color: Colors.textSecondary,
        fontSize: 20,
    },
    listItemTitle: {
        color: Colors.textPrimary,
        fontSize: 16,
        fontWeight: "500",
        flex: 1,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: Colors.border,
        alignItems: "center",
        justifyContent: "center",
    },
    checkboxChecked: {
        backgroundColor: Colors.primary,
        borderColor: Colors.primary,
    },
    listContainer: {
        paddingVertical: 8,
    },
    sheetError: {
        color: Colors.danger,
        fontSize: 14,
        marginBottom: 8,
        textAlign: "center",
    },
});
